"""Generate the self-contained Python script the ephemeral sandbox runs.

The script reads no input from anywhere except embedded constants — the
sandbox cannot reach the runner-service nor any other internal service.
It writes `/work/result.json` + screenshots/console.log on its own volume.
"""
from __future__ import annotations

import json
from typing import Any

# Keep aligned with playwright_runner.py's old supported set.
SUPPORTED_KEYWORDS = {
    "goto", "click", "fill", "type", "press", "wait_for",
    "expect_text", "expect_url", "screenshot", "reload",
}


def generate_script(test_case: dict[str, Any], target_url: str | None, timeout_seconds: int) -> str:
    # Use repr() of JSON strings — produces a properly-escaped Python literal
    # that survives any quote characters in the input. The previous r""" """
    # wrapper broke when the JSON contained embedded quote sequences.
    payload = test_case.get("payload", test_case)
    return _SCRIPT_TEMPLATE.format(
        test_case_json_literal=repr(json.dumps(payload)),
        target_url_json_literal=repr(json.dumps(target_url)),
        timeout_seconds=int(timeout_seconds),
        supported_keywords_literal=repr(sorted(SUPPORTED_KEYWORDS)),
    )


_SCRIPT_TEMPLATE = r'''#!/usr/bin/env python3
"""Generated by runner-service. Do not edit.

Runs inside an ephemeral container with no network access to QA/AQA internals.
Output: /work/result.json + /work/screenshots/*.png + /work/console.log
"""
import asyncio
import json
import os
import sys
import time
import traceback
from pathlib import Path

from playwright.async_api import async_playwright

WORK = Path("/work")
SHOTS = WORK / "screenshots"
SHOTS.mkdir(parents=True, exist_ok=True)

TEST_CASE = json.loads({test_case_json_literal})
TARGET_URL = json.loads({target_url_json_literal})
TIMEOUT_S = {timeout_seconds}
SUPPORTED = set({supported_keywords_literal})


def _result(status, error_message="", started=None):
    return {{
        "mode": "playwright_sandbox",
        "status": status,
        "duration_ms": int((time.time() - (started or time.time())) * 1000) if started else 0,
        "screenshots": [],
        "videos": [],
        "console_log_relpath": "console.log",
        "error_message": error_message,
        "screenshot_relpaths": [],
    }}


async def _do_step(page, step, idx):
    kw = step.get("keyword", "")
    args = step.get("args", []) or []
    if kw == "goto":
        await page.goto(args[0])
    elif kw == "click":
        await page.click(args[0])
    elif kw == "fill":
        await page.fill(args[0], args[1])
    elif kw == "type":
        await page.type(args[0], args[1])
    elif kw == "press":
        await page.press(args[0], args[1])
    elif kw == "wait_for":
        await page.wait_for_selector(args[0])
    elif kw == "expect_text":
        sel, text = args[0], args[1]
        actual = await page.inner_text(sel)
        if text not in actual:
            raise AssertionError(f"expect_text: {{text!r}} not in {{actual!r}}")
    elif kw == "expect_url":
        sub = args[0]
        if sub not in page.url:
            raise AssertionError(f"expect_url: {{sub!r}} not in {{page.url!r}}")
    elif kw == "screenshot":
        path = SHOTS / f"step_{{idx:02d}}.png"
        await page.screenshot(path=str(path))
    elif kw == "reload":
        await page.reload()
    else:
        raise ValueError(f"unsupported keyword: {{kw!r}}")


async def main():
    started = time.time()
    steps = TEST_CASE.get("steps", [])
    unsupported = [s.get("keyword") for s in steps if s.get("keyword") not in SUPPORTED]
    if unsupported:
        out = _result("error", f"unsupported keywords: {{unsupported}}", started)
        (WORK / "result.json").write_text(json.dumps(out))
        return

    console_lines = []
    page_errors = []
    status = "pass"
    error_message = ""

    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            ctx = await browser.new_context()
            page = await ctx.new_page()
            page.on("console", lambda msg: console_lines.append(f"{{msg.type}}: {{msg.text}}"))
            page.on("pageerror", lambda exc: page_errors.append(str(exc)))
            try:
                if TARGET_URL and not any(s.get("keyword") == "goto" for s in steps):
                    await page.goto(TARGET_URL)
                async def run_all():
                    for i, s in enumerate(steps):
                        await _do_step(page, s, i)
                await asyncio.wait_for(run_all(), timeout=TIMEOUT_S)
                final = SHOTS / "final.png"
                await page.screenshot(path=str(final))
            except asyncio.TimeoutError:
                status = "timeout"
                error_message = f"exceeded {{TIMEOUT_S}}s"
            except AssertionError as e:
                status = "fail"
                error_message = str(e)
            except Exception as e:
                status = "error"
                error_message = f"{{type(e).__name__}}: {{e}}"
            finally:
                try:
                    await ctx.close()
                finally:
                    await browser.close()
    except Exception as e:
        status = "error"
        error_message = f"playwright init failed: {{e}}"
        traceback.print_exc()

    (WORK / "console.log").write_text(
        "\n".join(console_lines + [f"[ERROR] {{x}}" for x in page_errors])
    )
    screenshots = sorted(p.name for p in SHOTS.glob("*.png"))
    out = {{
        "mode": "playwright_sandbox",
        "status": status,
        "duration_ms": int((time.time() - started) * 1000),
        "error_message": error_message,
        "screenshot_relpaths": screenshots,
        "console_log_relpath": "console.log",
    }}
    (WORK / "result.json").write_text(json.dumps(out))


if __name__ == "__main__":
    asyncio.run(main())
'''
